config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  resources :bands

  root "bands#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    has_many :concerts, -> { order(datetime: :desc) }, dependent: :destroy
    validates :name, presence: true, uniqueness: { case_sensitive: false }
    validates :debut, :crew, presence: true

    def last_concert_in_words(date)
        month = {
            1   => "enero",
            2   => "febrero",
            3   => "marzo",
            4   => "abril",
            5   => "mayo",
            6   => "junio",
            7   => "julio",
            8   => "agosto",
            9   => "septiembre",
            10  => "octubre",
            11  => "noviembre",
            12  => "diciembre"
        }

        day = {
            1   => "lunes",
            2   => "martes",
            3   => "míercoles",
            4   => "jueves",
            5   => "viernes",
            6   => "sábado",
            7   => "domingo"
        }
        
        "#{date.year}, #{day[date.wday]} #{date.day} de #{month[date.month]}"
    end
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :band

    validates :datetime, :duration, :assistants, presence: true
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: %i[ show edit update destroy ]

  # GET /bands or /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1 or /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands or /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: "Band was successfully created." }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1 or /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: "Band was successfully updated." }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1 or /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def band_params
      params.require(:band).permit(:name, :debut, :crew)
    end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
    @bands = Band.all
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:datetime, :duration, :assistants, :band_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/bands/_form.html.erb
<%= form_with(model: band) do |form| %>
  <% if band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
        <% band.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <span class="mr-2">Nombre</span>
    <%= form.text_field :name, class: "rounded p-2 w-full" %>
  </div>

  <div class="mb-2">
    <span class="mr-2">Integrantes</span>
    <%= form.number_field :crew, in: 1..100, class: "rounded p-2 w-full" %>
  </div>

  <div class="">
    <span class="mr-2">Debut</span>
    <%= form.date_field :debut, type: "date", class: "rounded p-2 w-full" %>
  </div>

  <div class="flex justify-center">
    <%= form.submit "Guardar", class: "py-1 rounded bg-gray-300 hover:bg-green-400 text-center mt-5 w-full" %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<div class="border-4 border-green-400 mx-auto rounded w-1/3 mt-20 bg-green-100 p-5 shadow-lg">
    <h1 class="text-3xl">Editando Banda</h1>
    <div class="flex justify-left mb-5">
        <%= link_to 'Mostrar', @band, class: "bg-green-400 mr-2 px-3 py-1 rounded hover:bg-black text-white hover:shadow text-sm" %>
        <%= link_to 'Volver', bands_path, class: "bg-green-400 px-3 py-1 rounded hover:bg-black text-white hover:shadow text-sm" %>
    </div>

    <%= render 'form', band: @band %>    
</div>

app/views/bands/index.html.erb
<div class="mx-12">
  <p id="notice"><%= notice %></p>

  <div class="grid grid-cols-2 h-12 mt-10 mb-2 sticky top-2 bg-gray-50 opacity-90">
    <div class="col-start">
      <span class="text-4xl pl-5 my-auto">Bandas</span>
    </div>
    <div class="col-end-4 my-auto">
      <%= link_to 'Nueva Banda', new_band_path, class: "transition duration-200 ease-in-out bg-gray-200 hover:bg-indigo-600 hover:text-white font-medium py-2 px-10 rounded" %>
    </div>
  </div>
  
  <div class="space-y-2 mb-10">
    <% @bands.each do |band| %>
      <div class="flex justify-between group bg-gray-100 rounded-lg transition-shadow	hover:shadow-inner">

        <div class="flex w-2/6 items-center p-4 pr-6 bg-gray-200 rounded-l-lg">
          <div class="mr-3">
            <div title="Editar">
              <%= link_to edit_band_path(band) do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 opacity-0 text-gray-300 hover:text-green-500 group-hover:opacity-100 transition duration-100 ease-in-out" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                </svg>
              <% end %>
            </div>
            
            <div title="Ver">
              <%= link_to band do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 opacity-0 text-gray-300 hover:text-blue-500 group-hover:opacity-100 transition duration-100 ease-in-out" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg>
              <% end %>
            </div>
          </div>
  
          <div class="grid grid-rows-2 grid-flow-col">
            <div class="text-lg font-medium">
              <%= band.name %>
            </div>
            <div class="text-sm">
              <%= band.crew %>
              <span>integrantes</span>
            </div>
          </div>
        </div>
        
        <div class="flex space-x-10 items-center">
          <div class="inline-block">
            <span class="block text-2xl">
              <%= band.concerts.count %>
            </span>
            <span class="block text-sm">conciertos</span>
          </div>
          <div class="inline-block">
            <span class="block text-2xl">
              <%= band.concerts.sum(:assistants) %>
            </span>
            <span class="block text-sm">total asistentes</span>
          </div>
          <div class="inline-block">
            <span class="block text-2xl">
              <%= band.debut %>
            </span>
            <span class="block text-sm">debut</span>
          </div>

        </div>


        <div class="self-center mr-5" title="Terminar Contrato">
          <%= link_to band, method: :delete, data: { confirm: 'Terminar contrato con esta banda?' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-300 hover:text-red-700 transition duration-100 ease-in-out" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/bands/new.html.erb
<div class="border-4 border-gray-400 mx-auto rounded w-1/3 mt-20 bg-gray-200 p-5 shadow-lg">
    <h1 class="text-3xl mb-5">Nueva Banda</h1>
    <%= render 'form', band: @band %>
    <%= link_to bands_path do %>
        <div class="py-1 mx-8 rounded bg-gray-300 hover:bg-gray-400 text-center mt-2 w-full mx-auto">
            <span>volver</span>
        </div>
    <% end %>
</div>

app/views/bands/show.html.erb
<div class="w-3/4 mx-auto mt-12">
  <p id="notice"><%= notice %></p>
  
  <div class="mb-5">
    <%= link_to 'Editar', edit_band_path(@band), class: "bg-gray-200 p-1 rounded hover:bg-green-400 hover:shadow" %>
    <%= link_to 'Volver', bands_path, class: "bg-gray-200 px-5 p-1 rounded hover:bg-black hover:text-white hover:shadow" %>
  </div>

  
  <div class="block mb-10">
    <div class="font-light">Viendo el perfil de:</div>
    <div class="text-5xl">
      <%= @band.name %>
    </div>
    <p>
      <span>Debutó el </span>
      <%= @band.debut %>
    </p>
  </div>
  
    <% if @band.concerts.count > 0 %>
      <div class="flex justify-between space-x-2 w-4/5 mb-5">
        <% today = Time.now %>
        <% start_month = Time.new(today.year, today.month, 1, 0, 0, 0) %>
        
        <div class="bg-gray-200 p-4 rounded-lg w-2/6">
          <h4 class="text-sm">Último concierto:</h4>
          <% if @band.concerts.where(datetime: @band.concerts.last.datetime..today).count > 0 %>
            <% last_concert = @band.concerts.where(datetime: @band.concerts.last.datetime..today).first.datetime %>
            <span class="text-2xl"> <%= @band.last_concert_in_words(last_concert) %> </span>
          <% else %>
            <span class="text-2xl">Sin conciertos pasados</span>
          <% end %>
        </div>
        
        <div class="bg-gray-200 p-4 rounded-lg">
          <h4 class="text-sm">Conciertos este mes:</h4>
          <span class="text-2xl">
            <%= @band.concerts.where(datetime: start_month..today).count %>
          </span>
        </div>

        <div class="bg-gray-200 p-4 rounded-lg">
          <h4 class="text-sm">Máximo asistentes:</h4>
          <span class="text-2xl"> <%= @band.concerts.maximum('assistants') %> </span>
        </div>
        
        <div class="bg-gray-200 p-4 rounded-lg">
          <h4 class="text-sm">Máxima duración:</h4>
          <span class="text-2xl"> <%= @band.concerts.maximum('duration') %> min </span>
        </div>
      </div>

      <table class="w-5/6 shadow-md">
        <thead>
          <tr class="text-left">
            <th class="pl-2 py-2 w-2/5">Fecha</th>
            <th class="py-2">Duración</th>
            <th class="py-2">Asistentes</th>
          </tr>
        </thead>
        <tbody>
          <% @band.concerts.each do |concert|  %>
            <tr class="bg-gray-100 border-2">
              <td class="pl-2 py-2 text-sm"><%= concert.datetime.strftime("%Y/%m/%d a las %H:%M ") %></td>
              <td class="py-2 text-sm"><%= concert.duration %> min</td>
              <td class="py-2 text-sm"><%= concert.assistants %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  
    <% else %>
      <div class="my-5">
        <div class="flex justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-2/6 w-2/6 stroke-current text-gray-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 5v2m0 4v2m0 4v2M5 5a2 2 0 00-2 2v3a2 2 0 110 4v3a2 2 0 002 2h14a2 2 0 002-2v-3a2 2 0 110-4V7a2 2 0 00-2-2H5z" />
          </svg>
        </div>
        <h4 class="select-none text-3xl font-thin	text-center text-gray-400">Sin conciertos aún</h4>
      </div>
    <% end %>
</div>

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <span class="mr-2">Fecha y hora</span>
    <%= form.datetime_field :datetime, type: "datetime-local", class: "rounded p-2 w-full" %>
  </div>

  <div class="mb-2">
    <span>Duración:</span>
    <%= form.number_field :duration, class: "rounded p-2 w-full" %>
  </div>

  <div class="mb-2">
    <span>Asistentes:</span>
    <%= form.number_field :assistants, class: "rounded p-2 w-full" %>
  </div>

  <div class="mb-2">
    <span>Banda</span>
    <%= form.collection_select(:band_id, Band.all, :id, :name, {}, {class: "w-full p-2"}) %>
  </div>

  <div class="flex justify-center">
    <%= form.submit "Guardar", class: "py-1 rounded bg-gray-300 hover:bg-green-400 text-center mt-5 w-full" %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<div class="border-4 border-green-400 mx-auto rounded w-1/3 mt-20 bg-green-100 p-5 shadow-lg">
    <h1 class="text-3xl">Editando Concierto</h1>
    <div class="flex justify-left mb-5">
    
    <div class="flex justify-left mb-5"></div>
        <%= link_to 'Mostrar', @concert,  class: "bg-green-400 mr-2 px-3 py-1 rounded hover:bg-black text-white hover:shadow text-sm" %>
        <%= link_to 'Volver', concerts_path, class: "bg-green-400 px-3 py-1 rounded hover:bg-black text-white hover:shadow text-sm" %>
    </div>
    
    <%= render 'form', concert: @concert %>

</div>

app/views/concerts/index.html.erb
<div class="mx-12">
  <p id="notice"><%= notice %></p>

  <div class="grid grid-cols-2 h-12 mt-10 mb-2 sticky top-2 bg-gray-50 opacity-90">
    <div class="col-start">
      <span class="text-4xl pl-5 my-auto">Conciertos</span>
    </div>
    <div class="col-end-4 my-auto">
      <%= link_to 'Nuevo concierto', new_concert_path, class: "transition duration-200 ease-in-out bg-gray-200 hover:bg-indigo-600 hover:text-white font-medium py-2 px-10 rounded" %>
    </div>
  </div>

  <div class="space-y-2 mb-10">
    <% (@concerts.order(datetime: :desc)).each do |concert| %>
    <div class="flex justify-between group bg-gray-100 rounded-lg transition-shadow	hover:shadow-inner px-5">
      <div class="mr-3 py-4 w-3/6">
        <div class="text-xl">
          <%= concert.datetime.strftime("%Y/%m/%d %H:%M ") %>
        </div>
        <div>
          <%= concert.duration %> min
        </div>
      </div>

      <div class="my-auto w-full">
        <div class="text-2xl">
          <%= concert.band.name %>
        </div>
        <div>
          <span>
            <%= concert.assistants %>
            asistentes
          </span>
        </div>
      </div>

      <div class="group my-auto space-x-4 w-5/6 flex justify-end">
        <div class="flex space-x-4 mr-8">
          <div title="Ver">
            <%= link_to concert do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 opacity-0 text-gray-400 hover:text-blue-400 group-hover:opacity-100" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
            <% end %>
          </div>
          
          <div title="Editar">
            <%= link_to edit_concert_path(concert) do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 opacity-0 text-gray-400 hover:text-green-400 group-hover:opacity-100" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
            <% end %>
          </div>
        </div>

        <span class="font-semibold text-gray-400 hover:text-red-800" title="Cancela este evento">
          <%= link_to 'cancelar evento', concert, method: :delete, data: { confirm: 'Are you sure?'} %>
        </span>
      </div>
      </div>
    <% end %>
  </div>

  <br>
</div>

app/views/concerts/new.html.erb
<div class="border-4 border-gray-400 mx-auto rounded w-1/3 mt-20 bg-gray-200 p-5 shadow-lg">
    <h1 class="text-3xl mb-5">Nuevo Concierto</h1>
    <%= render 'form', concert: @concert %>
    <%= link_to concerts_path do %>
        <div class="py-1 mx-8 rounded bg-gray-300 hover:bg-gray-400 text-center mt-2 w-full mx-auto">
            <span>volver</span>
        </div>
    <% end %>
</div>

app/views/concerts/show.html.erb
<div class="w-3/4 mx-auto mt-12">
  <p id="notice"><%= notice %></p>
  
  <div class="mb-5">
    <%= link_to 'Editar', edit_concert_path(@concert), class: "bg-gray-200 p-1 rounded hover:bg-green-400 hover:shadow" %>
    <%= link_to 'Volver', concerts_path, class: "bg-gray-200 px-5 p-1 rounded hover:bg-black hover:text-white hover:shadow" %>
  </div>

  <p>
    <strong>Fecha:</strong>
    <%= @concert.datetime %>
  </p>

  <p>
    <strong>Duración:</strong>
    <span>
      <%= @concert.duration %>
      min
    </span>
  </p>

  <p>
    <strong>Asistentes:</strong>
    <span>
      <%= @concert.assistants %>
      asistentes
    </span>
  </p>

  <p>
    <strong>Banda:</strong>
    <%= @bands.find_by(id: @concert.band_id).name %>
  </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Concert Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-50">
    <div class="p-2 bg-gray-900 inset-y-0 fixed shadow-lg w-52">
      <div class="w-12 h-12 mx-auto mt-3 bg-gradient-to-bl from-indigo-700 drop-shadow rounded-full text-white"></div>
      
      <div class="mt-8">
        <%= link_to bands_path, :action => 'index' do %>
        <div class="cursor-pointer px-5 py-2 rounded block flex bg-gray-800 transition duration-400 ease-in-out hover:bg-black hover:shadow mb-3">
          <span class="my-auto w-3 h-3 bg-gradient-to-bl from-purple-400 to-pink-500 rounded-full mr-3"></span>
          <span class="text-gray-50 select-none">Bandas</span>
        </div>
        <% end %>
        
        <%= link_to concerts_path, :action => 'index' do %>
          <div class="cursor-pointer px-5 py-2 rounded block flex bg-gray-800 transition duration-400 ease-in-out hover:bg-black hover:shadow">
            <span class="my-auto w-3 h-3 bg-gradient-to-bl from-green-400 to-blue-500 rounded-full mr-3"></span>
            <span class="text-gray-50 select-none">Conciertos</span>
          </div>
        <% end %>
      </div>
    </div>

    <div class="ml-52 flex justify-center">
      <div class="block w-5/6">
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>